version: '2'
services:
  web:
    image: registry.9418.club/app/wisecloud/ues/web:@{web_version}
    stdin_open: true
    tty: true
    volumes_from:
    - web-data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: web-data
  web-data:
    image: registry.9418.club/app/wisecloud/ues/web-data:@{web_version}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  wisecloud:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
