.catalog:
  name: "ues"
  version: @{module_version}
  description: "ues for wisecloud powerd by svicloud"
  uuid: ues-@{module_version}

version: '2'
services:
  web:
    scale: 1
    start_on_create: true
  web-data:
    scale: 1
    start_on_create: true
  wisecloud:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
